// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAExxpMbdEQkmWQWQPr8B0loDBFtLctQU',
    appId: '1:850799576690:web:bd28b7462f5b88a17024eb',
    messagingSenderId: '850799576690',
    projectId: 'penyapp-eb2c0',
    authDomain: 'penyapp-eb2c0.firebaseapp.com',
    storageBucket: 'penyapp-eb2c0.firebasestorage.app',
    measurementId: 'G-Y792EZJ2HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRa1wMmEVsMN2ln7v4BjZEdtRka4r6KrU',
    appId: '1:850799576690:android:72ec3f71182943d67024eb',
    messagingSenderId: '850799576690',
    projectId: 'penyapp-eb2c0',
    storageBucket: 'penyapp-eb2c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKGOf_krW8StdcWmufuGcSb1KJPZDOgpM',
    appId: '1:850799576690:ios:e35954a978fc4f017024eb',
    messagingSenderId: '850799576690',
    projectId: 'penyapp-eb2c0',
    storageBucket: 'penyapp-eb2c0.firebasestorage.app',
    iosBundleId: 'com.example.penyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKGOf_krW8StdcWmufuGcSb1KJPZDOgpM',
    appId: '1:850799576690:ios:e35954a978fc4f017024eb',
    messagingSenderId: '850799576690',
    projectId: 'penyapp-eb2c0',
    storageBucket: 'penyapp-eb2c0.firebasestorage.app',
    iosBundleId: 'com.example.penyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAExxpMbdEQkmWQWQPr8B0loDBFtLctQU',
    appId: '1:850799576690:web:2193cded41119af77024eb',
    messagingSenderId: '850799576690',
    projectId: 'penyapp-eb2c0',
    authDomain: 'penyapp-eb2c0.firebaseapp.com',
    storageBucket: 'penyapp-eb2c0.firebasestorage.app',
    measurementId: 'G-8F3H8KCPRM',
  );

}